import React, { useState, useMemo } from 'react';
import { Save, Copy, ChevronLeft, Layout, Table, BookOpen, Code, Check } from 'lucide-react';
import { clsx } from 'clsx';
import * as irabDataModule from '../data/irabData';
import { manualTemplates as initialTemplates } from '../data/manualTemplates';

export default function Studio() {
  const [activeTab, setActiveTab] = useState('roles'); // roles, signs, reasons, templates, export
  const [irabData, setIrabData] = useState(irabDataModule);
  const [templates, setTemplates] = useState(initialTemplates);
  const [copied, setCopied] = useState(false);

  // Helper to update deeply nested data
  const updateData = (key, value) => {
    setIrabData(prev => ({ ...prev, [key]: value }));
  };

  const updateTemplate = (id, field, value) => {
    setTemplates(prev => prev.map(t => t.id === id ? { ...t, [field]: value } : t));
  };

  // Generate JS code for irabData.js
  const generateIrabDataCode = () => {
    let code = `// ─── Generated by Erab Studio ──────────────────────────────────────────\n\n`;
    
    // Simplistic export generation
    const exportKeys = [
      'wordTypes', 'isimCategories', 'fiilCategories', 'hurufCategories', 
      'irabTypes', 'mabniSigns', 'mahalIrab', 'isimMurabRoles', 
      'isimMabniTypes', 'signsByIrab', 'reasons', 
      'fiilMadhiMabniOptions', 'fiilAmrMabniOptions'
    ];

    exportKeys.forEach(key => {
      code += `export const ${key} = ${JSON.stringify(irabData[key], null, 2)};\n\n`;
    });

    return code;
  };

  // Generate JS code for manualTemplates.js
  const generateTemplatesCode = () => {
    const categories = [
      { value: 'isim_khusus', label: '📚 Isim — Kasus Khusus' },
      { value: 'fiil_khusus', label: "📚 Fi'il — Kasus Khusus" },
      { value: 'jumlah',      label: '📜 Jumlah (Kalimat) dalam Mahall' },
      { value: 'tarkib',      label: '🔗 Tarkib (Susunan Khusus)' },
      { value: 'la_nafiyah',  label: '🚫 Laa Nafiyah Lil-Jins' },
    ];
    
    return `export const templateCategories = ${JSON.stringify(categories, null, 2)};\n\nexport const manualTemplates = ${JSON.stringify(templates, null, 2)};`;
  };

  const handleCopyCode = (code) => {
    navigator.clipboard.writeText(code).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const tabs = [
    { id: 'roles', label: 'Kedudukan (Roles)', icon: Layout },
    { id: 'signs', label: 'Tanda & Alasan', icon: Table },
    { id: 'templates', label: 'Manual Templates', icon: BookOpen },
    { id: 'export', label: 'Export Code', icon: Code },
  ];

  return (
    <div className="min-h-screen bg-slate-100 p-4 sm:p-8 font-sans">
      <div className="max-w-6xl mx-auto bg-white rounded-3xl shadow-xl overflow-hidden border border-slate-200">
        {/* Header */}
        <div className="bg-emerald-700 p-6 text-white flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <Code size={24} /> Erab Studio
            </h1>
            <p className="text-emerald-100 text-sm mt-1">Kelola data tata bahasa dan template secara visual.</p>
          </div>
          <button 
            onClick={() => window.location.href = '/'}
            className="flex items-center gap-2 bg-emerald-600 hover:bg-emerald-500 px-4 py-2 rounded-xl transition-all text-sm font-medium"
          >
            <ChevronLeft size={18} /> Kembali ke Aplikasi
          </button>
        </div>

        {/* Sidebar + Content */}
        <div className="flex flex-col md:flex-row min-h-[600px]">
          {/* Navigation */}
          <div className="w-full md:w-64 bg-slate-50 border-r border-slate-200 p-4 shrink-0">
            <div className="space-y-2">
              {tabs.map(tab => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={clsx(
                    "w-full flex items-center gap-3 px-4 py-3 rounded-2xl text-sm font-medium transition-all text-left",
                    activeTab === tab.id 
                      ? "bg-white text-emerald-700 shadow-sm border border-slate-200" 
                      : "text-slate-500 hover:bg-slate-100 hover:text-slate-700"
                  )}
                >
                  <tab.icon size={18} />
                  {tab.label}
                </button>
              ))}
            </div>
          </div>

          {/* Main Panel */}
          <div className="flex-1 p-6 overflow-x-auto">
            {activeTab === 'roles' && (
              <div className="space-y-6">
                <h2 className="text-xl font-bold text-slate-800">Isim Mu'rab Roles</h2>
                <div className="grid gap-4">
                  {irabData.isimMurabRoles.map((role, idx) => (
                    <div key={idx} className="bg-slate-50 p-4 rounded-2xl border border-slate-200 grid grid-cols-1 sm:grid-cols-3 gap-4">
                      <div>
                        <label className="block text-[10px] uppercase tracking-wider text-slate-400 font-bold mb-1">Label</label>
                        <input 
                          type="text" 
                          value={role.label} 
                          onChange={(e) => {
                            const next = [...irabData.isimMurabRoles];
                            next[idx] = { ...next[idx], label: e.target.value };
                            updateData('isimMurabRoles', next);
                          }}
                          className="w-full bg-white border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-emerald-500 outline-none"
                        />
                      </div>
                      <div>
                        <label className="block text-[10px] uppercase tracking-wider text-slate-400 font-bold mb-1">Arabic</label>
                        <input 
                          type="text" 
                          dir="rtl"
                          value={role.arabic} 
                          onChange={(e) => {
                            const next = [...irabData.isimMurabRoles];
                            next[idx] = { ...next[idx], arabic: e.target.value };
                            updateData('isimMurabRoles', next);
                          }}
                          className="w-full bg-white border border-slate-200 rounded-lg px-3 py-2 text-lg font-arabic focus:ring-2 focus:ring-emerald-500 outline-none"
                        />
                      </div>
                      <div>
                        <label className="block text-[10px] uppercase tracking-wider text-slate-400 font-bold mb-1">I'rab Type</label>
                        <select
                          value={role.irab}
                          onChange={(e) => {
                            const next = [...irabData.isimMurabRoles];
                            next[idx] = { ...next[idx], irab: e.target.value };
                            updateData('isimMurabRoles', next);
                          }}
                          className="w-full bg-white border border-slate-200 rounded-lg px-3 py-2 text-sm focus:ring-2 focus:ring-emerald-500 outline-none"
                        >
                          <option value="rafa">Rafa'</option>
                          <option value="nashab">Nashab</option>
                          <option value="jar">Jar</option>
                          <option value="all">Semua (Na'at/Athaf etc)</option>
                        </select>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === 'signs' && (
              <div className="space-y-6">
                <h2 className="text-xl font-bold text-slate-800">Tanda & Alasan</h2>
                <div className="space-y-8">
                  {Object.entries(irabData.signsByIrab).map(([type, signs]) => (
                    <div key={type} className="space-y-4">
                      <h3 className="font-bold text-emerald-600 uppercase tracking-widest text-xs">Signs for {type.toUpperCase()}</h3>
                      <div className="grid gap-3">
                        {signs.map((sign, idx) => (
                          <div key={idx} className="bg-slate-50 p-4 rounded-2xl border border-slate-100 flex flex-col gap-3">
                            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                              <input 
                                type="text" 
                                value={sign.label} 
                                onChange={(e) => {
                                  const next = { ...irabData.signsByIrab };
                                  next[type][idx].label = e.target.value;
                                  updateData('signsByIrab', next);
                                }}
                                placeholder="Label (Deskripsi)"
                                className="bg-white border border-slate-200 rounded-lg px-3 py-1.5 text-xs"
                              />
                               <input 
                                type="text" 
                                dir="rtl"
                                value={sign.arabic} 
                                onChange={(e) => {
                                  const next = { ...irabData.signsByIrab };
                                  next[type][idx].arabic = e.target.value;
                                  updateData('signsByIrab', next);
                                }}
                                placeholder="Arabic String"
                                className="bg-white border border-slate-200 rounded-lg px-3 py-1.5 text-lg font-arabic"
                              />
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === 'templates' && (
              <div className="space-y-6">
                <h2 className="text-xl font-bold text-slate-800">Manual Templates Editor</h2>
                <div className="grid gap-6">
                  {templates.map((template) => (
                    <div key={template.id} className="bg-slate-50 p-5 rounded-2xl border border-slate-200 space-y-3">
                      <div className="flex items-center justify-between">
                         <input 
                          type="text" 
                          value={template.title} 
                          onChange={(e) => updateTemplate(template.id, 'title', e.target.value)}
                          className="bg-transparent font-bold text-slate-700 outline-none focus:ring-b-2 focus:ring-emerald-500"
                        />
                        <span className="text-[10px] bg-slate-200 px-2 py-1 rounded-full text-slate-500 uppercase font-bold">{template.category}</span>
                      </div>
                      <textarea 
                        dir="rtl"
                        value={template.text}
                        onChange={(e) => updateTemplate(template.id, 'text', e.target.value)}
                        className="w-full bg-white border border-slate-200 rounded-xl px-4 py-3 text-lg font-arabic leading-loose h-32 focus:ring-2 focus:ring-emerald-500 outline-none"
                      />
                      <input 
                        type="text" 
                        value={template.hint}
                        onChange={(e) => updateTemplate(template.id, 'hint', e.target.value)}
                        className="w-full bg-white/50 border border-slate-200 rounded-lg px-3 py-2 text-xs text-slate-500 outline-none"
                      />
                    </div>
                  ))}
                </div>
              </div>
            )}

            {activeTab === 'export' && (
              <div className="space-y-8">
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <h3 className="font-bold text-slate-700">Code for irabData.js</h3>
                    <button 
                      onClick={() => handleCopyCode(generateIrabDataCode())}
                      className="flex items-center gap-1.5 text-xs bg-emerald-600 text-white px-3 py-1.5 rounded-lg hover:bg-emerald-700 transition-all font-bold"
                    >
                      {copied ? <Check size={14}/> : <Copy size={14}/>} {copied ? 'Copied' : 'Copy Code'}
                    </button>
                  </div>
                  <pre className="bg-slate-900 text-slate-300 p-6 rounded-2xl text-[10px] sm:text-xs overflow-x-auto max-h-[400px]">
                    {generateIrabDataCode()}
                  </pre>
                </div>

                 <div>
                  <div className="flex items-center justify-between mb-3">
                    <h3 className="font-bold text-slate-700">Code for manualTemplates.js</h3>
                    <button 
                      onClick={() => handleCopyCode(generateTemplatesCode())}
                      className="flex items-center gap-1.5 text-xs bg-emerald-600 text-white px-3 py-1.5 rounded-lg hover:bg-emerald-700 transition-all font-bold"
                    >
                      {copied ? <Check size={14}/> : <Copy size={14}/>} {copied ? 'Copied' : 'Copy Code'}
                    </button>
                  </div>
                  <pre className="bg-slate-900 text-slate-300 p-6 rounded-2xl text-[10px] sm:text-xs overflow-x-auto max-h-[300px]">
                    {generateTemplatesCode()}
                  </pre>
                </div>

                <div className="bg-amber-50 border border-amber-200 p-6 rounded-2xl text-amber-800 text-sm">
                  <h4 className="font-bold mb-2 cursor-default">⚠️ Cara Memperbarui Data:</h4>
                  <ol className="list-decimal list-inside space-y-1 opacity-90">
                    <li>Edit data di atas melalui form yang disediakan.</li>
                    <li>Salin (Copy) kode dari box hitam di atas.</li>
                    <li>Buka file <code className="bg-amber-100 px-1 rounded text-amber-900">src/data/irabData.js</code> di editor kode Anda.</li>
                    <li>Hapus seluruh isi file dan paste kode yang baru saja disalin.</li>
                    <li>Simpan file. Aplikasi akan otomatis terupdate!</li>
                  </ol>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
